apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-k8s-my-angular-app
  labels:
    app: docker-k8s-my-angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-k8s-my-angular-app

  template:
    metadata:
      labels:
        app: docker-k8s-my-angular-app
    spec:
      containers:
        - name: docker-k8s-my-angular-app
          image: srinivasnayak8/my-angular-app
          ports:
            - containerPort: 8090
